name: family_health_record
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  build_runner: ^2.6.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file_picker: ^10.2.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.1.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
